services:

  db:
    image: postgres:16
    container_name: clinic_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: clinic_user
      POSTGRES_PASSWORD: clinic_pass
      POSTGRES_DB: clinic_os
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - clinic_net

  redis:
    image: redis:alpine
    container_name: clinic_redis
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - clinic_net

  evolution:
    image: atendai/evolution-api:latest
    container_name: clinic_evolution
    restart: unless-stopped
    environment:
      AUTHENTICATION_API_KEY: supersecretkey
      AUTHENTICATION_TYPE: apikey
      AUTHENTICATION_API_KEY_ENABLED: "true"
      SERVER_TYPE: http
      SERVER_PORT: 8080
      CORS_ORIGIN: "*"
      LOG_BAILEYS: error
      NODE_OPTIONS: "--dns-result-order=ipv4first"
      CONFIG_SESSION_PHONE_VERSION: "2.3000.1023204200"

      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://clinic_user:clinic_pass@db:5432/clinic_os
      DATABASE_CONNECTION_CLIENT_NAME: evolution_api
      DATABASE_SAVE_DATA_INSTANCE: "true"

      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: redis://redis:6379/0
      CACHE_REDIS_PREFIX: evolution

    ports:
      - "8080:8080"

    depends_on:
      - db
      - redis

    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - clinic_net

  backend:
    build: .
    container_name: clinic_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      evolution:
        condition: service_healthy
    networks:
      - clinic_net

volumes:
  db_data:
  redis_data:


networks:
  clinic_net:
    driver: bridge
