services:
  db:
    image: postgres:16
    container_name: clinic_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - clinic_net
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: clinic_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - clinic_net

  backend:
    build: .
    container_name: clinic_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.docker
    networks:
      - clinic_net

volumes:
  db_data:
  redis_data:

networks:
  clinic_net:
    driver: bridge
